env:
  es6: true
  node: true
  jest/globals: true
extends: 'eslint:recommended'
plugins:
  - jest
parserOptions:
  sourceType: module
  ecmaVersion: 8
  impliedStrict: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - warn
    - always
  no-console:
    - off
  no-unused-vars:
    - warn
  jest/prefer-to-have-length:
    - warn
  jest/valid-expect:
    - error
  jest/no-identical-title:
    - error
